const express = require('express')
const router = express.Router()
const connection = require('../../Config/database')
const controllerAdmin = require('../../controllers/Administration')
const controlleruser = require('../../controllers/login')
router.get('/Administration/perfil', (req, res) => controllerAdmin.findcidade2(connection, req, res))
router.post('/Administration/perfil',(req, res) =>controlleruser.AlteraUserpassword(connection, req, res))
//router.get('/Administration/perfil/', (req, res) => res.render('Administration/perfil',{username:res.locals.user.username,email:res.locals.user.mail}))

module.exports = app => app.use('/', router)
